
name: Docker Hub Push

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}

  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bot-feur
    - name: Run the Docker image
      run: docker run --name bot-feur-runner --env TOKEN=${{ secrets.DISCORD_TOKEN }} bot-feur
